package_assets: on
embed_assets: on
compress_assets: on
gzip_assets: off

javascripts:
  default:
    - public/javascripts/jquery.js
    - public/javascripts/vendor/tipsy-0.1.7/javascripts/jquery.tipsy.js
    - public/javascripts/application.js

stylesheets:
  default:
    - public/stylesheets/reset.css
    - public/stylesheets/webfonts.css
    - public/stylesheets/main.css
    - public/stylesheets/navigation.css
    - public/stylesheets/cboxes.css
    - public/stylesheets/content.css
    - public/stylesheets/blog.css
    - public/stylesheets/coderay.css
    
    - public/javascripts/vendor/tipsy-0.1.7/stylesheets/tipsy.css
    - public/javascripts/vendor/mod/tipsy/tipsy.mod.css
